packages:
  - 'packages/*'
  - 'example'

catalog:
  'eslint': '^9.15.0'
  'typescript': '^5.6.3'
  'prettier': '^3.4.2'
  '@types/jest': '^29.5.14'
  'jest': '29.7.0'
  'ts-jest': '29.1.1'
  'intl-messageformat': '^10.7.18'
  '@formatjs/intl': '^3.1.8'
  'tslib': '^2.8.1'
  'react': '^19.0.0'
  'react-dom': '^19.0.0'
  '@types/react': '^19.0.0'
  '@types/react-dom': '^19.0.0'
