name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions: write-all

    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'
      
      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GRAVITY_UI_BOT_NPM_TOKEN }}

      - name: Print Environment Info
        run: pnpm exec nx report
        shell: bash

      - name: Unpublish empty 1.0.0 versions
        run: |
          echo "Unpublishing empty 1.0.0 versions..."
          npm unpublish -f @gravity-ui/i18n-types@1.0.0 || echo "Failed to unpublish @gravity-ui/i18n-types@1.0.0"
          npm unpublish -f @gravity-ui/i18n-core@1.0.0 || echo "Failed to unpublish @gravity-ui/i18n-core@1.0.0"
          npm unpublish -f @gravity-ui/i18n-react@1.0.0 || echo "Failed to unpublish @gravity-ui/i18n-react@1.0.0"
          npm unpublish -f @gravity-ui/i18n-node@1.0.0 || echo "Failed to unpublish @gravity-ui/i18n-node@1.0.0"
          npm unpublish -f @gravity-ui/i18n-cli@1.0.0 || echo "Failed to unpublish @gravity-ui/i18n-cli@1.0.0"
          npm unpublish -f @gravity-ui/i18n-babel-plugin@1.0.0 || echo "Failed to unpublish @gravity-ui/i18n-babel-plugin@1.0.0"
          npm unpublish -f @gravity-ui/i18n-optimize-plugin@1.0.0 || echo "Failed to unpublish @gravity-ui/i18n-optimize-plugin@1.0.0"
          npm unpublish -f @gravity-ui/eslint-plugin-i18n@2.0.0 || echo "Failed to unpublish @gravity-ui/eslint-plugin-i18n@2.0.0"
          echo "Unpublish attempts completed"
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GRAVITY_UI_BOT_NPM_TOKEN }}

      - name: Build packages
        run: pnpm exec nx run-many --target=build --all
        shell: bash

      - name: Publish packages
        run: pnpm exec nx release publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GRAVITY_UI_BOT_NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
